import Head from "next/head";
import { BackgroundImage, Box, Button, Flex, Text, Title } from "@mantine/core";
import Link from "next/link";
import { createStyles } from "@mantine/core";
import Typewriter from "typewriter-effect";
import React from "react";
import { motion } from "framer-motion";
import Image from "next/image";
// style component
const useStyles = createStyles((theme) => ({
  backgroundImage: {
    minHeight: "100vh",
    backgroundSize: "cover",
  },
  CreateAccountButton: {
    color: "white",
    backgroundColor: "#008A61",
    border: 0,
    cursor: "pointer",

    "&:hover": {
      backgroundColor: "white",
      color: "#008A61",
    },
    "@media (max-width: 800px)": {
      marginRight: "65px",
      flex: "0",
      position: "absolute",
      left: "142px",
    },
  },
  LoginButton: {
    color: "white",
    backgroundColor: "#008A61",
    border: 0,
    cursor: "pointer",

    "&:hover": {
      backgroundColor: "white",
      color: "#008A61",
    },
    "@media (max-width: 800px)": {
      marginRight: "65px",
      flex: "0",
      position: "absolute",
      left: "270px",
    },
  },
  logo: {
    flex: "1",
    fontFamily: "'Solitreo', cursive",
    fontSize: "30px",
    color: "white",
    margin: "20px",

    "@media (max-width: 800px)": {
      fontSize: "19px",
      marginTop: "30px",
      marginLeft: "10px",
    },
  },
  Introtitle: {
    fontFamily: "Heventica",
    position: "absolute",
    top: "30vh",
    left: "25vw",
    fontWeight: "bolder",
    fontSize: "80px",
    color: "white",
    "@media (max-width: 800px)": {
      fontSize: "50px",
      left: "8vw",
      top: "20vh",
    },
  },
  TypeWriterTitle: {
    position: "absolute",
    left: "20vw",
    "@media (max-width: 800px)": {
      fontSize: "50px",
      left: "10vw",
    },
  },
  studentInStress: {
    position: "relative",
    top: "70px",
    left: "80px",
    borderRadius: "29% 35% 25% 33% / 32% 32% 0% 40%",
  },
}));

// main function
export default function Home() {
  const { classes } = useStyles();

  return (
    <>
      <Head>
        <title>doSmartStudy</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Solitreo&display=swap');
        </style>
      </Head>
      <section>
        <Box sx={{ minHeight: "100vh", width: "100%" }}>
          <BackgroundImage
            src='/dssStudy-1.png'
            className={classes.backgroundImage}>
            {/* flex for logo and buttons */}
            <Flex
              mih={50}
              gap='sm'
              justify='flex-end'
              align='flex-start'
              direction='row'
              wrap='wrap'>
              <Text className={classes.logo}>doSmartStudy</Text>
              <Link href='/CreateAccount'>
                <Button mt='20px' className={classes.CreateAccountButton}>
                  Create Account
                </Button>
              </Link>
              <Link href='/Login'>
                <Button m='20px' className={classes.LoginButton}>
                  Login
                </Button>
              </Link>
            </Flex>
            {/* flex for introduction */}
            <Title order={1} className={classes.Introtitle}>
              Are You Preparing For Competitive Exam Like
              <div className={classes.TypeWriterTitle}>
                <Typewriter
                  options={{
                    strings: ["UPSE ?", "CAT ?", "GATE ?", "IIT-JEE ?"],
                    autoStart: true,
                    loop: true,
                  }}
                />
              </div>
            </Title>
          </BackgroundImage>
        </Box>
      </section>
      <Box
        sx={{
          minHeight: "100vh",
          backgroundColor: "black",
        }}>
        <Flex>
          <Image
            src='/womanFustration.jpg'
            alt='student in stress'
            width={500}
            height={500}
            className={classes.studentInStress}
          />
          {/* </Flex>
        <Flex> */}
          <Text color='white'>Item 1</Text>
          <Text color='white'>Item 2</Text>
          <Text color='white'>Item 3</Text>
        </Flex>
      </Box>
    </>
  );
}
